version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: snippet-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    network_mode: host

  backend:
    build: ./backend
    container_name: snippet-backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    network_mode: host

  mongo:
    image: mongo:6
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    network_mode: host

volumes:
  mongo-data:
